"""create products prices cart items

Revision ID: 97a2ddf501d7
Revises: dba27cf924da
Create Date: 2026-09-28 23:08:36.843217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a2ddf501d7'
down_revision: Union[str, Sequence[str], None] = 'dba27cf924da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.CheckConstraint("category IN ('produce', 'dairy', 'bakery', 'pantry')", name='ck_products_category'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cart_items',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity BETWEEN 1 AND 99', name='ck_cart_items_quantity_range'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'product_id')
    )
    op.create_table('product_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('regular_price', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Integer(), nullable=True),
    sa.Column('deal_quantity', sa.Integer(), nullable=True),
    sa.Column('deal_price', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(deal_quantity IS NULL) = (deal_price IS NULL)', name='ck_product_prices_deal_complete'),
    sa.CheckConstraint('deal_quantity IS NULL OR (deal_quantity >= 2 AND deal_price > 0)', name='ck_product_prices_deal_valid'),
    sa.CheckConstraint('regular_price > 0', name='ck_product_prices_regular_positive'),
    sa.CheckConstraint('sale_price IS NULL OR (sale_price > 0 AND sale_price < regular_price)', name='ck_product_prices_sale_below_regular'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_prices_product_observed', 'product_prices', ['product_id', 'observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_prices_product_observed', table_name='product_prices')
    op.drop_table('product_prices')
    op.drop_table('cart_items')
    op.drop_table('products')
    # ### end Alembic commands ###
