"""add product package

Revision ID: c0196e652646
Revises: 97a2ddf501d7
Create Date: 2026-09-28 23:19:21.914034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

PACKAGES = (
    "round", "long", "bunch", "tray", "carton", "tub", "cup", "block",
    "egg_carton", "loaf", "bag", "box", "bottle", "can", "jar",
)


# revision identifiers, used by Alembic.
revision: str = 'c0196e652646'
down_revision: Union[str, Sequence[str], None] = '97a2ddf501d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('package', sa.String(length=20), server_default='box', nullable=False))
    op.create_check_constraint(
        'ck_products_package', 'products', f"package IN ({', '.join(repr(p) for p in PACKAGES)})"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_products_package', 'products', type_='check')
    op.drop_column('products', 'package')
    # ### end Alembic commands ###
