"""create users sessions avatars

Revision ID: dba27cf924da
Revises: 
Create Date: 2026-09-28 22:11:35.413178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba27cf924da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_users_username_lower', 'users', [sa.literal_column('lower(username)')], unique=True)
    op.create_table('avatars',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('body_type', sa.String(length=20), nullable=False),
    sa.Column('skin_color', sa.String(length=7), nullable=False),
    sa.Column('shirt_color', sa.String(length=7), nullable=False),
    sa.Column('hat', sa.String(length=20), nullable=True),
    sa.Column('cart_style', sa.String(length=20), nullable=False),
    sa.Column('cart_color', sa.String(length=7), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("body_type IN ('round', 'tall', 'small')", name='ck_avatars_body_type'),
    sa.CheckConstraint("cart_style IN ('classic', 'basket', 'racer')", name='ck_avatars_cart_style'),
    sa.CheckConstraint("hat IS NULL OR hat IN ('cap', 'beanie', 'chef')", name='ck_avatars_hat'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('avatars')
    op.drop_index('uq_users_username_lower', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
