"""create trips

Revision ID: f69b837c491b
Revises: c0196e652646
Create Date: 2026-09-28 23:36:11.218300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f69b837c491b'
down_revision: Union[str, Sequence[str], None] = 'c0196e652646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('savings', sa.Integer(), nullable=False),
    sa.CheckConstraint('item_count > 0', name='ck_trips_item_count_positive'),
    sa.CheckConstraint('total >= 0 AND savings >= 0', name='ck_trips_amounts_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trips_user_checked_out', 'trips', ['user_id', 'checked_out_at'], unique=False)
    op.create_table('trip_items',
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('savings', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_trip_items_quantity_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trip_id', 'position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_items')
    op.drop_index('ix_trips_user_checked_out', table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
